services:
  assert-cdn:
    build:
      context: .
      dockerfile: ./asset-cdn/Dockerfile
      platforms:
        - linux/amd64
    image: ghcr.io/lucsoft/asset-cdn
    volumes:
      - cache:/app/cache
    ports:
      - "8000:8000"
  a-game:
    build:
      context: .
      dockerfile: ./Dockerfile
      platforms:
        - linux/amd64
    image: ghcr.io/lucsoft/block-game
    ports:
      - "5173:80"
volumes:
  cache:
